# Generated by Django 4.2.1 on 2023-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg1fVKRv4HsD3ESQtMcrv5u6ZcM9socXpQrUKSyh_E-NckPTmXF5RL7hg-M364_rehkPg&usqp=CAU', max_length=500),
        ),
    ]
